#!/usr/bin/env bash
# Read /etc/passwd line by line
while IFS=: read -r username password uid gid full_name home shell; do
    # If the full_name field is empty, set it to the username
    if [ -z "$full_name" ]; then
        full_name="$username"
    fi

    # Print the story for this user
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $full_name"
done < /etc/passwd
