#!/usr/bin/env bash
# The gang members

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID INFO HOME_DIR COMMAND_SHELL; do
    echo "The user \"$USERNAME\" is part of the \"$GROUP_ID\" gang, lives in \"$HOME_DIR\" and rides \"$COMMAND_SHELL\". \"$USER_ID\"'s place is protected by the passcode \"$PASSWORD\", more info about the user here: \"$INFO\""
done < /etc/passwd
